<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_s</name>
   <tag></tag>
   <elementGuidId>e042ac75-5662-446f-8769-d7937f9e4e4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ybar-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ybar-search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>39a04459-5176-40df-a785-7c4d1fa9a3e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>02c979ec-42e4-4645-b267-9196733c15fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ybar-search</value>
      <webElementGuid>7a98f437-ff21-4900-943d-1b25ed017656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rapid-noclick-resp _yb_1fy0v </value>
      <webElementGuid>e1a2569e-f9ac-4743-b78f-af9d97f2cbc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>639424e3-47a9-47ca-b2e3-4f8adaf2e160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>2b189a72-5f69-4fdc-ae52-f4aa5d82a4fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ylk</name>
      <type>Main</type>
      <value>slk:websrch;elm:search;elmt:icon;sec:ybar;subsec:searchbox;itc:0;tar:search.yahoo.com;</value>
      <webElementGuid>8da79fb8-33c5-479b-9c4c-3b2eb3ade7be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rapid_p</name>
      <type>Main</type>
      <value>257</value>
      <webElementGuid>c275bd7d-08b9-4ca8-ac5b-3460eca774c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-v9y</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0abe813d-6b8c-4b98-9c7a-bab1a6cf1f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ybar-search&quot;)</value>
      <webElementGuid>ce193810-f5b2-46e9-a050-c232d9a7cb48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ybar-search']</value>
      <webElementGuid>8b52f77a-9ed5-4b66-8a89-0be481f8d710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ybar-sf']/div[4]/button</value>
      <webElementGuid>abced52d-5df2-450d-8a47-0b349aea8dbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>582afa22-8137-41c3-ac3d-bc893e7a7929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'ybar-search']</value>
      <webElementGuid>220b4679-6ab9-4155-9a74-a08b6bea7255</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
