<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_s</name>
   <tag></tag>
   <elementGuidId>67d35b80-9fab-48a0-8e2e-1b4fa885d2b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ybar-sbq</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ybar-sbq']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a2cd0ff-4d32-4aed-8c61-4289cb00a9d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>622b81bb-6a56-44be-a090-cf6c0fc9ae01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_yb_fsw74  _yb_ha1fz  </value>
      <webElementGuid>5547e981-3818-4c30-8641-9653fbf32128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ybar-sbq</value>
      <webElementGuid>1ebd21af-d7fd-4ec5-8991-9487bddebdd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>3a7f88c6-fe75-45a4-a9f8-088ed0ed7448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>07d7732c-277c-4936-b541-30fe4ac881c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ylk</name>
      <type>Main</type>
      <value>sec:ybar;slk:websrch;subsec:searchbox;elm:search;elmt:input;itc:0;</value>
      <webElementGuid>a942ce24-4380-4ab3-ad7b-5ba6790c920d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search the web</value>
      <webElementGuid>31bd4a90-9adc-4f02-9e7a-b99978a9b8ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rapid_p</name>
      <type>Main</type>
      <value>254</value>
      <webElementGuid>0fa352ed-9282-48f4-b102-f33571178ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-v9y</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>503c996b-2635-49da-aea7-19f08b77b97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>2c8a1faa-324a-48fe-ade0-2edde8e5c0fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>both</value>
      <webElementGuid>0c7f3d13-0dcc-4b1f-b248-d7f4cf896c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9b3cd65e-1ce9-41a9-b37f-4fd390989601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ybar-sbq&quot;)</value>
      <webElementGuid>c28896c5-79ae-458b-92a1-be02df3f61f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ybar-sbq']</value>
      <webElementGuid>be8031e4-0a44-4e78-8495-71605d11faad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ybar-sf']/input</value>
      <webElementGuid>8e0220d2-f3dd-467a-8d0c-20e37e2f581d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2d4ed756-44c0-4124-ad62-ddee949daa39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ybar-sbq' and @name = 'p' and @placeholder = 'Search the web']</value>
      <webElementGuid>a5257fdd-1233-406a-88bd-7eef72d3ac62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
